version: '2.1'
services:
  # bench:
  #   image: bench-service:latest
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - "/tmp:/tmp"
  #   environment:
  #     OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
  #     BASE_PATH: "/tmp"
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
